server:
  port: 8888
spring:
  datasource:
    type : com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.151:1521:ORCL
    username: chinaoly
    password: chinaoly
    druid :
      maxWait : 500
      max-active : 500
      max-total : 500
mybatis:
  type-aliases-package : com.chinaoly.frm.security.entity
