server:
  port: 7080
spring:
  application:
    name: eureka-client1
  http :
    encoding :
      force : true
      charset : UTF-8
      enabled : true
  datasource:
    type : com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.151:1521:ORCL
    username: chinaoly
    password: chinaoly
    druid :
      maxWait : 500
      max-active : 500
      max-total : 500
  redis :
      host : 192.168.1.146
      database : 0
      port : 6379
      timeout : 100000
      pool :
        max-idle : 10000
        min-idle : 50
mybatis:
  type-aliases-package : com.chinaoly.frm.security.entity
logging :
  config : classpath:logback-spring.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
